#!/bin/bash

# initialize the system

mysql_opts="-e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=myapp -e MYSQL_USER=auth -e MYSQL_PASSWORD=auth"

# create & run
docker network create auth
docker run --name auth-db --network auth ${mysql_opts} -d mysql:8 --default-authentication-plugin=mysql_native_password
